<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>04-Promise-handler-error</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<body>
  <h1>Promise-handler-error</h1>
  <div id="content">
    <div class="spinner-border" style="dispaly: none" role="status">
      <span class="sr-only">Loading...</span>
    </div>
  </div>
  <script>
    function get(url) {
      // 返回一个 Promise
      return new Promise(function(resolve, reject) {
        const req = new XMLHttpRequest();
        req.open('GET', url);

        req.onload = function() {
          if (req.status === 200) {
            resolve(req.response);
          } else {
            reject(Error(req.statusText));
          }
        }

        // 处理网络错误
        req.onerror = function() {
          reject(Error('Network Error'));
        }

        // 发起请求
        req.send();
      })
    }  

    function getJSON(url) {
      document.querySelector('.spinner-border').style.display = "block";
      return get(url).then(JSON.parse);
    }

    function addHtmlToPage(str) {
      const div = document.createElement('div');
      div.innerHTML = str;
      document.querySelector('#content').appendChild(div);
    }
    function addTexdtToPage(str) {
      const div = document.createElement('div');
      div.innerHTML = str;
      document.querySelector('#content').appendChild(div);
    }

    // 调用
    getJSON('story.json').then(function(response) {
      console.log('Success!', response);
      // return getJSON(response.chapterUrls[01])
      return getJSON(response.chapterUrls[03]) // 测试请求失败
      // 如果请求 story.chapterUrls[0] 失败（http 500 或者用户掉线什么的）了，它会跳过之后所有针对成功的回调，包括 getJSON 中将响应解析为 JSON 的回调，和这里把第一张内容添加到页面里的回调。JavaScript 的执行会进入 catch 回调。
    }).then(function(response) {
      console.log('Got chapter 1', response);
      addHtmlToPage(response.html);
    }).catch(function(err) {
      console.log(err); 
      // 如果只是要捕捉异常做记录输出，不打算在用户界面上对错误进行反馈的话，只要抛出 Error 就行了
      // throw (err);
      addTexdtToPage('Failed to show chapter')
    }).then(function() { // 捕获完错误后，下面的代码继续执行
      document.querySelector('.spinner-border').style.display = "none";
    })
  </script>
</body>
</html>